[theme]
base                     = "dark"
primaryColor             = "#3562E9"
backgroundColor          = "#121317"
secondaryBackgroundColor = "#1b1c22"
textColor                = "#f0f2f5"
font                     = "sans serif"

[server]
headless = true
